{include file="common/header"}
<div class="content-wrapper">
    {include file="member/nav"/}
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="nav-tabs-custom">
                    {include file="member/tabs"/}
                    <div class="tab-content">
                        <form method="post" class="form-horizontal form" id="post_form">
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    编辑会员等级
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">级别名称</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="title" value="{$item['title']}" placeholder="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">开通所需金额</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="have_money" value="{$item['have_money']}" placeholder="需要修改密码时请输入，否则请留空">
                                        </div>
                                    </div>
                                   
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">一级返佣</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="repay_1" value="{$item['repay_1']}" placeholder="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">二级返佣</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="repay_2" value="{$item['repay_2']}" placeholder="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">三级返佣</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="repay_3" value="{$item['repay_3']}" placeholder="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">补贴</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <input type="text" class="form-control" name="butie" value="{$item['butie']}" placeholder="">
                                        </div>
                                    </div>

                                    
                                    <div class="form-group">
                                        <label class="col-xs-12 col-sm-3 col-md-2 control-label">是否生效</label>
                                        <div class="col-sm-6 col-xs-12">
                                            <label class="radio-inline">
                                                <input type="radio" name="is_effect" value="1" {$item['is_effect']?'checked':''}>
                                                正常
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="is_effect" value="0" {$item['is_effect']?'':'checked'}>
                                                禁用
                                            </label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-6 col-xs-12 col-sm-offset-2">
                                            <input type="hidden" name="id" value="{$item['id']?$item['id']:0}">
                                            <button type="button" name="submit" class="btn btn-primary">提交</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <script type="text/javascript">
                            $(function () {
                                //提交分类信息
                                $("button[name='submit']").click(function () {
                                    $.post(
                                        window.location.href,
                                        $('#post_form').serialize(),
                                        function (res) {
                                            message(res.message,res.redirect,res.type)
                                        },'json'
                                    );
                                });
                            });
                        </script>
                    </div>
                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
</div>
{include file="common/footer"}
