<!DOCTYPE HTML>
<html>
	<head>
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>{$site['seo_title']?$site['seo_title']:''}</title>
		<meta name="Description" content="{$site['seo_description']?$site['seo_description']:''}" />
		<meta name="Keywords" content="{$site['seo_keywords']?$site['seo_keywords']:''}" />
		<link rel="stylesheet" href="/static/home/mobile/css/bootstrap.css">
		<link rel="stylesheet" href="/static/home/mobile/css/font-awesome.min.css">
		<link href="/static/home/mobile/css/reset_5.css" rel="stylesheet" type="text/css" />
		<link href="/static/home/mobile/css/style.css?v=21019" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="/static/home/mobile/css/new_page.css?v=2" />
		<link rel="stylesheet" href="/static/home/mobile/css/swiper.min.css" />
		<style type="text/css">
			.new-main {
				padding-bottom: 40px;
			}
            .load-more{
                margin-top: -10px;
                margin-bottom: 30px;
                height: 30px;
                line-height: 30px;
                text-align: center;
                background: #ffffff;
            }
		</style>
        <!-- 弹出层 -->
        <link rel="stylesheet" href="/static/plugins/dialog/css/dialog.css" />
        <script type="text/javascript" src="/static/home/mobile/js/jquery-2.0.3.min.js"></script>
        <script src="/static/plugins/dialog/js/dialog.js"></script>
        <!-- 弹出层 -->
        <script type="text/javascript" src="/static/plugins/clipboard.min.js"></script>
        <script type="text/javascript" src="/static/home/mobile/js/swiper.min.js"></script>
        <script type="text/javascript" src="/static/home/mobile/js/global.js"></script>
        <script type="text/javascript" src="/static/home/mobile/js/index/jquery.flexslider-min.js"></script>
        <link rel="stylesheet" href="/static/home/mobile/js/index/flexslider.min.css" />
        <link rel="stylesheet" href="/static/home/mobile/js/index/index.css?v=1">
	</head>
    <body class="new-body">

      
   <section id="banner">
   <div class="flexslider"> 
      <ul class="slides"> 
        <li><a href="#"><img src="http://1.so4.top/Public/upload/images/1903/30/5154135.jpg"></a></li> 
        <li><a href="#"><img src="http://1.so4.top/Public/upload/images/1903/30/5154135.jpg"></a></li> 
      </ul> 
   </div>
   </section>
    
   <div class="banner-bottom">
        <img src="/static/home/mobile/js/index/home-banner-bottom.png">
    </div>
    <section id="container">
      <div class="app_download">
      <img src="/static/home/mobile/js/index/horn.png" alt="">
      <div id="notice" class="swiper-container swiper-container-vertical">
            <div class="swiper-wrapper">
               {if !empty($notices)}
                    {volist name="notices" id="notice"}
                        <div class="swiper-slide swiper-slide-duplicate">
                            <a id="slide_href" href="/home/notice/detail/id/{$notice['id']}.html" hid="12">{$notice['title']}</a>
                        </div>
                    {/volist}
                {/if}
               </div>
            </div>
      </div>
       <div class="index_menu">
      <ul>
      <li><a href="#"><img src="/static/home/mobile/js/index/menu2.png"><b>会员专区</b></a></li>
      <li><a href="#"><img src="/static/home/mobile/js/index/menu1.png"><b>新作榜</b></a></li>
      <li><a href="#"><img src="/static/home/mobile/js/index/menu3.png"><b>排行榜</b></a></li>
      <li><a href="#"><img src="/static/home/mobile/js/index/menu4.png"><b>分类</b></a></li>
      </ul>
     </div>
      <div class="clear"></div>
      <div class="h1_title">
      <h4>推荐任务</h4>
      </div>
    

      </section>
     {if !empty($tasks)}   
     <div class="list-block">
      <ul>
      {volist name="tasks" id="task" key="task_index"}  
      <li style="height: 100px;">
      <a href="/home/task/detail/id/{$task['id']}.html" class="userlogo"><img src="{$task['avatar']}" alt=""></a>
      <a href="/home/task/detail/id/{$task['id']}.html" class="title">
      <div class="subtitle" style="font-size: 15px;font-weight: bold;">{$task['title']}</div>
      <div class="money" style="color:#FF2424;font-weight: bold;font-size: 15px;">赏  {$task['unit_price']}元</div>
      <div class="keywords" style="margin-top: 10px;margin-bottom: 10px;"><span class="blue">{$categories[0]['title']}</span> <span class="yellow"> {if !empty($task['appName'])}
                              {$task['appName']}
                            {else/}
                                应用名称
                            {/if}</span> <span class="red" style="position: absolute;right:0;margin-right: 0px">{$task['give_credit1']}积分</span>
        </div>  
        <div class="desc" style="color:#5f4b4b"><span>编号：{$task['id']}</span>  <span style="margin-left: 26px;"> {$task['join_num']}人已赚到赏金</span>　<span style="position: absolute;right:0">剩余{$task['ticket_num']-$task['join_num']}份 </span></div>

      </a> 
      </li>
      {/volist}
  </ul>
</div>
   <div class="clear"></div>
    {/if}
      <div style="height:85px;"></div>
   {include file='common/footer'}   
   <script>
    $(function() { 
      $(".flexslider").flexslider({
		animation: "slide",
		slideshowSpeed: 3000,
		directionNav: false, 
		pauseOnHover:true,
		}); 
    }); 
   </script>
       <script type="text/javascript" src="/static/home/mobile/js/index.js"></script>
    {$site['baidu_stat']?$site['baidu_stat']:''}
    {$site['baidu_chat']?$site['baidu_chat']:''}
      
    </body>
</html>