<footer id="footer-bar" lang="{$controller}">
      <ul id="tabbar">
      <li><a href="/"><img src="/static/home/mobile/js/index/hom1{if condition="in_array($controller,array('index'))"}_on{/if}.png"><b>首页</b></a></li>
      <li><a href="/home/task/index.html"><img src="/static/home/mobile/js/index/hom2{if condition="in_array($controller,array('task'))"}_on{/if}.png"><b>任务大厅</b></a></li>
      <li><a href="/home/invite.html"><img src="/static/home/mobile/js/index/hom3{if condition="in_array($controller,array('invite'))"}_on{/if}.png"><b>邀请好友</b></a></td>
      <li><a href="/home/account.html"><img src="/static/home/mobile/js/index/hom4{if condition="in_array($controller,array('account','charge','fans','vip','feedback','feedback','notice','help'))"}_on{/if}.png"><b>我的</b></a></li>
      </ul>
</footer>