<footer class="new-footer">
    <ul>
        <li>
            <a href="/index.html">
                <img {if condition="$controller neq 'index'"}class="gray"{/if} src="/static/home/mobile/picture/home.png" />
                <span>首页</span>
            </a>
        </li>
        <li>
            <a href="/">
                
                <span></span>
            </a>
        </li>
        <li>
            <a href="/task.html">
                <span class="add-span"></span>
                <span>任务大厅</span>
            </a>
        </li>
        <li>
            <a href="/">
                
                <span></span>
            </a>
        </li>
        <li>
            <a href="/home/account.html">
                <img {if condition="$controller neq 'account'"}class="gray"{/if}  src="/static/home/mobile/picture/users.png" />
                <span>个人中心</span>
            </a>
        </li>
    </ul>
</footer>